- name: Install nginx
  apt:
    name: "{{ nginx_package }}"
    state: present


- name: Ensure nginx is running
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: true


- name: Deploy HTML
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart nginx
